<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/jquery-1.9.1.min.js"><\/script>')</script>
<script src="http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.js"></script>
<script src="{{ asset('theme/zoe/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('theme/zoe/js/jquery.fitvids.js') }}"></script>
<script src="{{ asset('theme/zoe/js/jquery.sequence-min.js') }}"></script>
<script src="{{ asset('theme/zoe/js/jquery.bxslider.js') }}"></script>
<script src="{{ asset('theme/zoe/js/main-menu.js') }}"></script>
<script src="{{ asset('theme/zoe/js/template.js') }}"></script>