<?php
namespace BetoGaizinTheme\Http\Controllers;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Validator;
use Illuminate\Support\Str;
use Mail;
use BetoGaizinTheme\Mail\MyEmail;
class HomeController extends \Zoe\Http\ControllerFront
{
    public $config_language = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->config_language = app()->config_language;
    }

    public function getHome()
    {

    }

    public function getCategoryProduct($slug,$id){
        $results = DB::table('shop_product')->where('category_id',$id)->get()->all();
        return $this->render('home.category-product', [
            'results'=>$results
        ]);
    }

    public function getItemProduct($slug,$id){
        $result = DB::table('shop_product')->where('id',$id)->get()->all();
        $item = isset($result[0])?$result[0]:null;
        return $this->render('home.item-product', [
            'item'=>$item,
            'categorys'=>$item != null ?DB::table('shop_product')->where('category_id',$item->category_id)->orderByRaw('RAND()')->limit(10)->get()->all():[]
        ]);
    }

}