<?php

namespace Admin\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use Admin\Http\Models\Menu;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
class MenuController extends \Zoe\Http\ControllerBackend
{
    public function getCrumb()
    {
        $this->breadcrumb("Menu List", ('backend:menu:list'));
        return $this;
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->data['language'] = config('zoe.language');
        $this->data['configs'] = config_get("config", "system");
        $this->data['current_language'] =
            isset($this->data['configs']['core']['site_language']) ?
                $this->data['configs']['core']['site_language'] :
                config('zoe.default_lang');
    }

    public function ajax(Request $request)
    {
        $post = $request->all();
        if (isset($post['act'])) {
            if ($post['act'] == "info") {
                $data = $post['data'];


                $filter = [
                    'name' => 'required',
                    'description' => 'required',
                ];
                if(
                    isset($this->data['configs']['core']['language']['multiple'])
                    && isset($data['type']) &&  isset($this->data['configs']['core']['menu']['type'][$data['type']])
                ){
                    $newFilter = [];
                    foreach ($this->data['language'] as $lang => $_language) {
                        if(
                            isset($this->data['configs']['core']['language']['lists']) &&
                            (is_string($this->data['configs']['core']['language']['lists']) &&
                                $this->data['configs']['core']['language']['lists'] == $_language['lang']||
                                is_array($this->data['configs']['core']['language']['lists']) &&  in_array($_language['lang'],$this->data['configs']['core']['language']['lists'])) ){
                            foreach ($filter as $col=>$value){
                                $newFilter[$col.'_'.$lang] = $value;
                            }
                        }

                    }

                    $filter = $newFilter;
                }
                $rules = [];

                $validator = Validator::make($data,$filter);
                if ($validator->passes()) {
                    $oke = true;
                    if (isset($data["data"])) {
                        $type = $data['type'];
                        if (isset(app()->getConfig()['modules']['admin.menu'][$type]['rules'])) {
                            $rules = (app()->getConfig()['modules']['admin.menu'][$type]['rules']);
                            $validator = Validator::make($data['data'], $rules);
                            $oke = $validator->passes();
                        }
                    }
                    if ($oke) {
                        $create = false;
                        if (isset($data) && isset($data['id']) && $data['id'] != 0) {
                            $menu = Menu::find($data['id']);
                        } else {

                            $menu = new Menu();
                            $create = true;
                        }


                        $menu->name = isset($data['name'])?"":"";
                        if(!empty($menu->name)){
                            $slug = Str::slug($data['name'], '-');
                            $menu->slug = $slug;
                        }else{
                            $menu->slug  = "";
                        }
                        $menu->parent_id = 0;
                        $menu->description = isset($data['description'])?$data['description']:"";
                        $menu->status = $data['status'];
                        $menu->type = $data['type'];
                        $menu->type_link = $data['type_link'];
                        $menu->link = $data['link'];
                        $menu->router_name = $data['router_name'];
                        $menu->icon = "";
                        $menu->featured = $data['featured'];
                        $menu->order = 0;
                        $menu->is_default = 0;
                        $menu->data = isset($data["data"]) && is_array($data["data"]) ? serialize($data["data"]) : serialize([]);

                        DB::beginTransaction();
                        try {
                            $menu->save();

                            foreach ($this->data['language'] as $lang => $_language) {
                                if (isset($data['name_' . $lang])) {
                                    $menu->table_translation_model()->updateOrInsert(
                                        [
                                            '_id' => $menu->id,
                                            'lang_code' => $lang
                                        ],
                                        [
                                            'name' => $data['name_' . $lang],
                                            'slug' =>Str::slug($data['name_' . $lang], '-','ja'),
                                            'description' => $data['description_' . $lang]
                                        ]
                                    );
                                }
                            }
                            $request->session()->flash('success', $create == "create"?z_language('Faq is added successfully'):z_language('Faq is updated successfully'));
                            DB::commit();
                            return response()->json(['success' => $data,'status'=>true]);
                        } catch (\Exception $ex) {
                            $validator->getMessageBag()->add('id', $ex->getMessage());
                            DB::rollBack();
                        }
                        return response()->json(['error' => $validator->errors(), 'data_rules' => $rules]);
                    } else {
                        return response()->json(['error' => $validator->errors(), 'data_rules' => $rules]);
                    }
                } else {
                    return response()->json(['error' => $validator->errors(), 'data_rules' => $rules]);
                }

            } else if ($post['act'] == "position") {

                $data = $post['data'];
                \Illuminate\Support\Facades\DB::beginTransaction();
                try {
                    if (isset($data['id']) && $data['id'] != 0) {
                        $menu = Menu::find($data['id']);
                        $menu->delete();
                    }
                    config_set("menu", $data['type'], ['data' => $data['pos']]);
                    \Illuminate\Support\Facades\DB::commit();
                    return response()->json(['error' => 0, 'data' => $data]);
                } catch (\Exception $ex) {
                    \Illuminate\Support\Facades\DB::rollBack();
                    return response()->json(['error' => 1]);
                }

            } else if ($post['act'] == "edit") {
                $data = $post['data'];
                $menu = Menu::find($data['id']);
                if (isset($this->data['configs']['core']['language']['multiple'])) {
                    $trans = $menu->table_translation_model()->where(['_id' => $data['id']])->get();
                    foreach ($trans as $tran) {
                        $menu->offsetSet("name_" . $tran->lang_code, $tran->name);
                        $menu->offsetSet("slug_" . $tran->lang_code, $tran->slug);
                        $menu->offsetSet("description_" . $tran->lang_code, $tran->description);
                    }
                }
                return response()->json(['data' => $menu]);
            } else if ($post['act'] == "nestable") {
                $data = $post['data'];
                $type = $data['type'];

                $this->data['menu'] = get_menu_type($type);

                echo $this->nestable(config_get("menu", $type), 0, true);
            }
        }
    }

    private $html = "";
    public $ids = [];
    private function nestable($nestable, $parent_id = 0, $root = false)
    {
        $html = '<ol class="dd-list">';

        foreach ($nestable as $key => $item) {
            if (isset($this->data['menu'][$item['id']])) {
                $this->ids[$item['id']] = 1;
                $html .= '<li class="dd-item dd3-item" data-id="' . $item['id'] . '" data-name="' . $this->data['menu'][$item['id']]->name . '" parent_id="' . $parent_id . '">';
                $html .= '<div class="dd-handle dd3-handle"></div>
		        <div class="dd3-content">' . $this->data['menu'][$item['id']]->name . '</div>';
                $html .= "<div class='dd3-tool'><button class='btn btn-primary btn-xs edit'>" . "<i class='fa fa-edit'></i>" . "</button><button class='btn  btn-default btn-xs delete'>" . "<i class='fa fa-remove'></i>" . "</button></div>";
                unset($this->data['category'][$item['id']]);
                if (isset($item["children"])) {
                    $html .= $this->nestable($item["children"], $item['id'],false);
                }
                $html .= '</li>';
            }
        }
        if ($root) {
            foreach ($this->data['menu'] as $k => $item) {
                $oke = !isset($this->ids[$item->id]) ;
                if($oke){
                    $html .= '<li class="dd-item dd3-item" data-id="' . $item->id . '" data-name="' . $item->name . '" parent_id="0">';
                    $html .= '<div class="dd-handle dd3-handle"></div><div class="dd3-content">' . $item->name . '</div>';
                    $html .= "<div class='dd3-tool'><button class='btn btn-primary btn-xs edit'>" . "<i class='fa fa-edit'></i>" . "</button><button class='btn  btn-default btn-xs delete'>" . "<i class='fa fa-remove'></i>" . "</button></div>";
                    $html .= '</li>';
                }
            }
        }
        $html .= '</ol>';
        return $html;
    }

    public function show(Request $request)
    {
        $type = isset($request->route()->defaults['type']) ? $request->route()->defaults['type'] : 'menu';

        $views = "";
        if (isset(app()->getConfig()['modules']['admin.menu'][$type]['views'])) {
            if (isset(app()->getConfig()['modules']['admin.menu'][$type]['views'])) {
                $views = (app()->getConfig()['modules']['admin.menu'][$type]['views']);
            }
            if (isset(app()->getConfig()['modules']['admin.menu'][$type]['breadcrumb'])) {
                $breadcrumb = (app()->getConfig()['modules']['admin.menu'][$type]['breadcrumb']);
                $this->breadcrumb($breadcrumb['name'], ($breadcrumb['route']));
            }
        } else {
            $this->getCrumb();
        }
        $this->breadcrumb("Menu", ('backend:menu:list'));

        $this->data['menu'] = get_menu_type($type);

        $this->data['nestable'] = $this->nestable(config_get("menu", $type), 0, true);
        $this->data['type'] = $type;
        $this->data['views'] = $views;
        $this->data['pages'] = [];

        return $this->render('menu.show',[],'backend');
    }
    public function list(){
        return $this->render('menu.list');
    }
}