<?php

namespace Admin\Http\Controllers;

use Admin\Http\Models\PageModel;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Validator;
class PageController extends \Zoe\Http\ControllerBackend
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->data['language'] = config('zoe.language');
        $this->data['configs'] = config_get("config", "system");
        $this->data['current_language'] =
            isset($this->data['configs']['core']['site_language']) ?
                $this->data['configs']['core']['site_language'] :
                config('zoe.default_lang');
    }

    public function getCrumb()
    {
        $this->sidebar('backend:page:list');
        $this->breadcrumb(z_language("Page"), ('backend:page:list'));
        return $this;
    }
    public function ajax(Request $request){
        $key = base64_decode($request->header('KEY'));
        if(Auth::user()->IsAcl()){

        }
        return response()->json([]);
    }
    public function list(Request $request)
    {
        $this->getcrumb();
        $search = $request->query('search', "");
        $status = $request->query('status', "");
        $date = $request->query('date', "");
        $config = config_get('option', "core:page");
        $item = isset($config['pagination']['item']) ? $config['pagination']['item'] : 20;
        $models = DB::table('page');
        if (!empty($search)) {
            $models->where('title', 'like', '%' . $search);
        }
        if (!empty($status) || $status != "") {
            $models->where('status', $status);
        }


        $lang = $this->data['current_language'];
        $models->join('page_translation as rt', 'rt._id', '=', 'page.id');
        $models->where('rt.lang_code', $lang);

        $models->orderBy('id', 'desc');
        return $this->render('page.list', [
            'models' => $models->paginate($item),
            'callback'=>[
                "func_slug"=>function($model){
                    $url = url($model->slug);
                    return "<a href='".$url."'>".$url."</a>";
                }
            ]
        ]);
    }
    public function create(Request $request)
    {
        $this->getcrumb()->breadcrumb("Create Page", false);
        return $this->render('page.create', []);
    }

    public function edit($id)
    {
        $this->getcrumb()->breadcrumb("Edit Page", false);
        $page = PageModel::find($id);
        $composers = unserialize($page->composers);
        $_composers = [];
        foreach ($composers as $key=>$value){
            $_composers[$key] = base64_decode($value);
        }
        $page->composers = $_composers;

        if (isset($this->data['configs']['core']['language']['multiple'])) {
            $trans = $page->table_translation_model()->where(['_id' => $id])->get();
            foreach ($trans as $tran) {
                $page->offsetSet("title_" . $tran->lang_code, $tran->title);
                $page->offsetSet("content_" . $tran->lang_code, $tran->content);
                $page->offsetSet("description_" . $tran->lang_code, $tran->description);
            }
        }

        return $this->render('page.edit', ["page" => $page]);
    }

    public function delete(Request $request)
    {
        $id = $request->id;
        $ref = $request->ref;
        $model = PageModel::find($id);
        if($model){
            $model->delete();
        }
        if($ref){
            return redirect($ref);
        }else{
            return redirect(route("backend:page:list", []));
        }
    }

    public function status()
    {

    }

    public function store(Request $request)
    {
        $items = $request->all();

        $filter = [
            'title' => 'required|max:255',
        ];
        if(isset($this->data['configs']['core']['language']['multiple'])){
            $newFilter = [];
            foreach ($this->data['language'] as $lang => $_language) {
                if(
                    isset($this->data['configs']['core']['language']['lists']) &&
                    (is_string($this->data['configs']['core']['language']['lists']) &&
                        $this->data['configs']['core']['language']['lists'] == $_language['lang']||
                        is_array($this->data['configs']['core']['language']['lists']) &&  in_array($_language['lang'],$this->data['configs']['core']['language']['lists'])) ){
                    foreach ($filter as $col=>$value){
                        $newFilter[$col.'_'.$lang] = $value;
                    }
                }
            }
            $filter = $newFilter;
        }
        $filter = array_merge($filter,[
            'router' => 'required',
            'slug' => 'required',
        ]);
        $type = "create";
        if (isset($items) && isset($items['id'])) {
            $page = PageModel::find($items['id']);
            if($page->slug != $items['slug']){
                $filter['slug'] = 'required|max:255|unique:page';
            }
            $type = "edit";
        } else {
            $page = new PageModel();
            $filter['slug'] = 'required|max:255|unique:page';
        }
        $validator = Validator::make($items,$filter, [
            'title.required' => z_language('The title field is required.'),
            'router.required' => z_language('The title field is required.'),
//            'content.required' => z_language('The content field is required.'),
//            'content.description' => z_language('The description field is required.'),
            'slug.required' => z_language('The slug field is required.'),
            'slug.unique' => z_language('The slug has already been taken.'),
        ]);

        if ($validator->fails()) {
            return back()
                ->withErrors($validator)
                ->withInput();
        }
        try {
            $page->title = isset($items['title'])?$items['title']:"";
            $page->slug =$items['slug'];
            $page->router =  Str::slug($items['router'], '_');
            $page->description = isset($items['description'])?$items['description']:"";
            $page->content = isset($items['content'])?htmlspecialchars_decode($items['content']):"";
            $page->status = $items['status'];
            $page->composers = serialize(isset($items['composers'])?$items['composers']:[]);
            $page->is_mutile_lang = isset($this->data['configs']['core']['language']['multiple'])?1:0;

            DB::beginTransaction();
            $file = new \Illuminate\Filesystem\Filesystem();
            try{
                $page->save();

                if(isset($this->data['configs']['core']['language']['multiple'])){

                    foreach ($this->data['language'] as $lang => $_language) {
                        if (isset($items['title_' . $lang])) {
                            $page->table_translation_model()->updateOrInsert(
                                [
                                    '_id' => $page->id,
                                    'lang_code' => $lang
                                ],
                                [
                                    'title' => $items['title_' . $lang],
                                    'description' => $items['description_' . $lang],
                                    'content' => htmlspecialchars_decode($items['content_' . $lang])
                                ]
                            );
                            $path = storage_path('app/views/pages/');
                            if (!$file->isDirectory($path)) {
                                $file->makeDirectory($path);
                            }
                            $file->put($path . '/' . $lang.'_'.$page->router  . '.blade.php', html_entity_decode($items['content_' . $lang]));
                        }
                    }

                }
                $request->session()->flash('success', $type == "create"?z_language('Page is added successfully'):z_language('Page is updated successfully'));
                DB::commit();
                return back();
            }catch (\Exception $ex){
                $validator->getMessageBag()->add('router', $ex->getMessage());
                DB::rollBack();

            }
        }catch (\Exception $ex){
            $validator->getMessageBag()->add('router', $ex->getMessage());
        }
        return back()
            ->withErrors($validator)
            ->withInput();

    }
}