<?php

namespace Admin\Http\Controllers;

use Illuminate\Http\Request;
use Validator;
use Admin\Http\Models\Menu;
use Illuminate\Support\Str;

class SidebarController extends \Zoe\Http\ControllerBackend
{
    public function getCrumb()
    {
        $this->breadcrumb("Sidebar", route('backend:menu:list'));
        return $this;
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function ajax(Request $request)
    {
        $post = $request->all();
        if (isset($post['act'])) {
            if ($post['act'] == "info") {
                $data = $post['data'];
                $validator = Validator::make($data, [
                    'name' => 'required',
                    'description' => 'required',
                ]);
                $rules = [];
                if ($validator->passes()) {
                    $oke = true;
                    if (isset($data["data"])) {
                        $type = $data['type'];
                        if (isset(app()->getConfig()['modules']['admin.menu'][$type]['rules'])) {
                            $rules = (app()->getConfig()['modules']['admin.menu'][$type]['rules']);
                            $validator = Validator::make($data['data'], $rules);
                            $oke = $validator->passes();
                        }
                    }
                    if ($oke) {
                        $create = false;
                        if (isset($data) && isset($data['id']) && $data['id'] != 0) {
                            $menu = Menu::find($data['id']);
                        } else {

                            $menu = new Menu();
                            $create = true;
                        }
                        $slug = Str::slug($data['name'], '-');
                        $menu->name = $data['name'];
                        $menu->slug = $slug;
                        $menu->parent_id = 0;
                        $menu->description = $data['description'];
                        $menu->status = $data['status'];
                        $menu->type = $data['type'];
                        $menu->icon = "";
                        $menu->featured = $data['featured'];
                        $menu->order = 0;
                        $menu->is_default = 0;
                        $menu->data = isset($data["data"]) && is_array($data["data"]) ? serialize($data["data"]) : serialize([]);
                        $menu->save();
                        return response()->json(['success' => $data]);
                    } else {
                        return response()->json(['error' => $validator->errors(), 'data_rules' => $rules]);
                    }
                } else {
                    return response()->json(['error' => $validator->errors(), 'data_rules' => $rules]);
                }

            } else if ($post['act'] == "position") {

                $data = $post['data'];
                \Illuminate\Support\Facades\DB::beginTransaction();
                try {
                    if (isset($data['id']) && $data['id'] != 0) {
                        $menu = Menu::find($data['id']);
                        $menu->delete();
                    }
                    config_set("menu", $data['type'], ['data' => $data['pos']]);
                    \Illuminate\Support\Facades\DB::commit();
                    return response()->json(['error' => 0, 'data' => $data]);
                } catch (\Exception $ex) {
                    \Illuminate\Support\Facades\DB::rollBack();
                    return response()->json(['error' => 1]);
                }

            } else if ($post['act'] == "edit") {
                $data = $post['data'];
                $menu = Menu::find($data['id']);
                return response()->json(['data' => $menu]);
            } else if ($post['act'] == "nestable") {
                $data = $post['data'];
                $type = $data['type'];
                $this->data['menu'] = get_category_type($type);
                echo $this->nestable(config_get("menu", $type), 0, true);
            }
        }
    }

    private $html = "";

    private function nestable($nestable, $parent_id = 0, $root = false)
    {
        $html = '<ol class="dd-list">';
        foreach ($nestable as $key => $item) {
            if (isset($this->data['menu'][$item['id']])) {
                $html .= '<li class="dd-item dd3-item" data-id="' . $item['id'] . '" data-name="' . $this->data['menu'][$item['id']]->name . '" parent_id="' . $parent_id . '">';
                $html .= '<div class="dd-handle dd3-handle"></div>
		        <div class="dd3-content">' . $this->data['category'][$item['id']]->name . '</div>';
                $html .= "<div class='dd3-tool'><button class='btn btn-primary btn-xs edit'>" . "<i class='fa fa-edit'></i>" . "</button><button class='btn  btn-default btn-xs delete'>" . "<i class='fa fa-remove'></i>" . "</button></div>";
                unset($this->data['category'][$item['id']]);
                if (isset($item["children"])) {
                    $html .= $this->nestable($item["children"], $item['id']);
                }
                $html .= '</li>';
            }
        }
        if ($root) {
            foreach ($this->data['menu'] as $k => $item) {
                $html .= '<li class="dd-item dd3-item" data-id="' . $item->id . '" data-name="' . $item->name . '" parent_id="0">';
                $html .= '<div class="dd-handle dd3-handle"></div>
		        <div class="dd3-content">' . $item->name . '</div>';
                $html .= "<div class='dd3-tool'><button class='btn btn-primary btn-xs edit'>" . "<i class='fa fa-edit'></i>" . "</button><button class='btn  btn-default btn-xs delete'>" . "<i class='fa fa-remove'></i>" . "</button></div>";
                $html .= '</li>';
            }
        }
        $html .= '</ol>';
        return $html;
    }

    public function list(Request $request)
    {
        $type = isset($request->route()->defaults['type']) ? $request->route()->defaults['type'] : 'menu';
        $views = "";

        if (isset(app()->getConfig()['modules']['admin.menu'][$type]['views'])) {
            if (isset(app()->getConfig()['modules']['admin.menu'][$type]['views'])) {
                $views = (app()->getConfig()['modules']['admin.menu'][$type]['views']);
            }
            if (isset(app()->getConfig()['modules']['admin.menu'][$type]['breadcrumb'])) {
                $breadcrumb = (app()->getConfig()['modules']['admin.menu'][$type]['breadcrumb']);
                $this->breadcrumb($breadcrumb['name'], route($breadcrumb['route']));
            }
        } else {
            $this->getCrumb();
        }

        $this->breadcrumb("Menu", route('backend:menu:list'));
        $this->data['menu'] = get_menu_type($type);
        $this->data['nestable'] = $this->nestable(config_get("menu", $type), 0, true);

        $this->data['type'] = $type;
        $this->data['views'] = $views;
        $this->data['pages'] = \Admin\Http\Models\PageModel::where('status',1)->get();

        return $this->render('sidebar.lists');
    }

}