<?php
namespace MissTerry\Http\Controllers;

use Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use \PhpOffice\PhpSpreadsheet;
use \PhpOffice\PhpSpreadsheet\Style\Border;
use \PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Admin\Http\Controllers\DashboardController as DashboardC;

class DashboardController extends DashboardC{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->data['language'] = config('zoe.language');
        $this->data['configs'] = config_get("config", "system");
        $this->data['current_language'] =
            isset($this->data['configs']['core']['site_language']) ?
                $this->data['configs']['core']['site_language'] :
                config('zoe.default_lang');
    }

    public function analytics(Request $request){
        $data = $request->all();
        $datas = [];
        \DB::enableQueryLog();
        $type = "";
        $response = [];
        if(isset($data['act'])){
            if($data['act'] == 'line'){
                if(isset($data['type'])){
                    $type = $data['type'];
                    DB::connection()->enableQueryLog();
                    $room_id = $data['room_id'];
                    $month = isset($data['month'])?$data['month']:date('m');
                    $admin_id = base64_decode($data['user_id']);
                    $results = [];

                    $excel = DB::table('cms_miss_booking');
                    $excel->where('status','1');

                    if(!empty($room_id)){
                        $excel->where('company',$room_id);
                    }
                    if($type == 'week'){
                        $date_start = date("Y-m-d", strtotime('monday this week'));
                        $date_end = date("Y-m-d", strtotime('sunday this week'));

                        $excel->where('created_at','>=',$date_start." 00:00:00");
                        $excel->where('created_at','<=',$date_end." 23:59:59");
                    }
                    else if($type == 'month'){
                        $date_start = date('Y').'-01-01';
                        $date_end = date('Y').'-12-31';;
                        $excel->where('created_at','>=',$date_start." 00:00:00");
                        $excel->where('created_at','<=',$date_end." 23:59:59");
                    } else if($type == 'year'){
                        $date_start = date('Y',strtotime('-5 year', time())).'-01-01';
                        $date_end =  date('Y',strtotime('+5 year', time())).'-12-31';
                        $excel->where('created_at','>=',$date_start." 00:00:00");
                        $excel->where('created_at','<=',$date_end." 23:59:59");
                    }else{

                        $date_start = date('Y').'-'.($month<10?"0".$month:$month).'-01';
                        $date_end = date('Y-m-d',strtotime('last day of this month', strtotime($date_start)));

                        $excel->where('created_at','>=',$date_start." 00:00:00");
                        $excel->where('created_at','<=',$date_end." 23:59:59");
                        $type = "day";
                    }
                    $results = $excel->orderBy('created_at')->get()->all();

                    foreach ($results as $key=>$value){
                        $key = '';
                        if ($type == 'month') {
                            $key = date('Y-m', strtotime($value->created_at)) . "-01";
                            $score = strtotime($key);
                        } else if ($type == 'year') {
                            $key = date('Y', strtotime($value->created_at));
                            $score = strtotime($key);
                        }else if ($type == 'week') {
                            list($start_date, $end_date) = $this->x_week_range($value->created_at);
                            $key = $start_date.' '.$end_date;
                            $score = strtotime($start_date)+strtotime($end_date);
                        }
                        else{
                            $key = date('Y-m-d', strtotime($value->created_at));
                            $score = strtotime($key);
                        }
                        if(!isset($datas[$key])){
                            $datas[$key] = [
                                "count"=>0,
                                "rate"=>0,
                                $type =>$key,
                                "score"=>$score
                            ];
                        }
                        $datas[$key]["count"]++;
                        $datas[$key]["rate"]+= $value->price;
                    }
                    usort($datas, function ($element1,$element2) use ($type){
                        return $element1["score"] - $element2["score"];
                    });
                    $response = [
                        "lists"=>$datas,
                        "sql"=>logs_sql(),
                        'xkey'=>$type
                    ];
                }
            }else if($data['act'] == 'circle'){
                if(isset($data['type'])){
                    $type = $data['type'];
                    $roles = DB::table('admin')->get()->keyBy('id');

                    $company = $data['conpany'];
                    $admin_id = "";
                    $results = [];
                    $totals = 0;
                    if($company != 'KOGYJA'){
                        $excel = DB::table('shop_order_excel');
                        $excel->where('fullname','!=','');
                        $excel->where('public','1');
                        if(!empty($admin_id)){
                            $excel->where('admin_id',$admin_id);
                        }
                        if(!empty($company)){
                            $excel->where('company',$company);
                        }else {
                            $excel->where('company', '!=', 'KOGYJA');
                        }
                        if($type == 'week'){
                            $date_start = date('Y-m').'-01';
                            $date_end = date('Y-m-d',strtotime('last day of this month', time()));
                            $excel->where('order_create_date','>=',$date_start." 00:00:00");
                            $excel->where('order_create_date','<=',$date_end." 23:59:59");
                        }
                        else if($type == 'month'){
                            $date_start = date('Y').'-01-01';
                            $date_end = date('Y').'-12-31';;
                            $excel->where('order_create_date','>=',$date_start." 00:00:00");
                            $excel->where('order_create_date','<=',$date_end." 23:59:59");
                        } else if($type == 'year'){
                            $date_start = date('Y',strtotime('-5 year', time())).'-01-01';
                            $date_end =  date('Y',strtotime('+5 year', time())).'-12-31';
                            $excel->where('order_create_date','>=',$date_start." 00:00:00");
                            $excel->where('order_create_date','<=',$date_end." 23:59:59");
                        }else{
                            $date_start = date('Y-m').'-01';
                            $date_end = date('Y-m-d',strtotime('last day of this month', time()));
                            $excel->where('order_create_date','>=',$date_start." 00:00:00");
                            $excel->where('order_create_date','<=',$date_end." 23:59:59");
                            $type = "day";
                        }
                        $results = $excel->orderBy('order_create_date')->get()->all();
                    }
                    foreach ($results as $key=>$value){
                        $key = $value->admin_id;

                        if(!isset($datas[$key])){
                            $datas[$key] = [
                                "count"=>0,
                                "rate"=>0,
                                $type =>$key
                            ];
                            $datas[$key]['name'] = $roles[$key]->username;
                        }
                        $totals++;
                        $datas[$key]["count"]++;
                        $datas[$key]["rate"]+= $value->order_price;
                    }
                    if(empty($company) || $company == 'KOGYJA') {
                        $excel = DB::table('shop_order_excel');
                        $excel->where('fullname', '!=', '');
                        $excel->where('public', '1');
                        $excel->where('type', 'Footer');
                        if (!empty($admin_id)) {
                            $excel->where('admin_id', $admin_id);
                        }
                        $excel->where('company', 'KOGYJA');
                        if($type == 'week'){
                            $date_start = date('Y-m').'-01';
                            $date_end = date('Y-m-d',strtotime('last day of this month', time()));
                            $excel->where('order_create_date','>=',$date_start." 00:00:00");
                            $excel->where('order_create_date','<=',$date_end." 23:59:59");
                        }
                        else if($type == 'month'){
                            $date_start = date('Y').'-01-01';
                            $date_end = date('Y').'-12-31';
                            $excel->where('order_create_date','>=',$date_start." 00:00:00");
                            $excel->where('order_create_date','<=',$date_end." 23:59:59");
                        } else if($type == 'year'){
                            $date_start = date('Y',strtotime('-5 year', time())).'-01-01';
                            $date_end =  date('Y',strtotime('+5 year', time())).'-12-31';
                            $excel->where('order_create_date','>=',$date_start." 00:00:00");
                            $excel->where('order_create_date','<=',$date_end." 23:59:59");
                        }else{
                            $date_start = date('Y-m').'-01';
                            $date_end = date('Y-m-d',strtotime('last day of this month', time()));
                            $excel->where('order_create_date','>=',$date_start." 00:00:00");
                            $excel->where('order_create_date','<=',$date_end." 23:59:59");
                            $type = "day";
                        }
                        $results = $excel->orderBy('order_create_date')->get()->all();

                        foreach ($results as $key => $value) {
                            $key = $value->admin_id;
                            if (!isset($datas[$key])) {
                                $datas[$key] = [
                                    "count" => 0,
                                    "rate" => 0,
                                    $type => $key,
                                ];
                                $datas[$key]['name'] = $roles[$key]->username;

                            }
                            $totals++;
                            $datas[$key]["count"]++;
                            $datas[$key]["rate"] += $value->order_price;
                        }
                    }
                    $response = [
                        "lists"=>$datas,
                        "sql"=>logs_sql(),
                        'totals'=>$totals
                    ];
                }
            }
        }
        return response()->json($response);
    }
    function x_week_range($date) {
        $ts = strtotime($date);
        $start = (date('w', $ts) == 0) ? $ts : strtotime('last sunday', $ts);
        $start = strtotime('+1 day',$start);
        return array(date('Y-m-d', $start), date('Y-m-d', strtotime('next sunday', $start)));
    }
    public function list(Request $request)
    {
        $date_start = $request->get('date_start',date('Y-m-d'));
        $date_end = $request->get('date_end',date('Y-m-d'));
        $models = DB::table('miss_room as room');
        $lang = $this->data['current_language'];
        $models->join('miss_room_translation as rt', 'rt.room_id', '=', 'room.id');
        $models->where('rt.lang_code', $lang);
        $rooms = $models->get()->all();
        $this->data['analytics']['category'] = [];
        $user_id = null;
        \DB::enableQueryLog();

        foreach($rooms as $category){
            $query = DB::table('miss_booking')
                ->where('status',1)
                ->where('room_id',$category->id);
            if(!empty($date_start) && !empty($date_end)){
                $query->where('created_at','>=',$date_start." 00:00:00");
                $query->where('created_at','<=',$date_end." 23:59:59");
            }
            $this->data['analytics']['category'][$category->id] = [];
            $this->data['analytics']['category'][$category->id]['data'] = $category;
            $this->data['analytics']['category'][$category->id]['count'] = $query->count();
            $this->data['analytics']['category'][$category->id]['price'] =  $query->sum('price');
        }

        $total = DB::table('miss_booking')->where('status',1);

        if(!empty($date_start) && !empty($date_end)){
            $total->where('created_at','>=',$date_start." 00:00:00");
            $total->where('created_at','<=',$date_end." 23:59:59");
        }
        $this->data['analytics']['total']['success'] = $total->count();

        $total1 = DB::table('miss_booking')->where('status',0);

        $this->data['analytics']['total']['fail'] = $total1->count();
        $this->data['analytics']['total']['total'] = $this->data['analytics']['total']['success'] +  $this->data['analytics']['total']['fail'];

        $total = DB::table('miss_booking')->where('status',1);
//        if(!empty($date_start) && !empty($date_end)){
//            $total->where('created_at','>=',$date_start." 00:00:00");
//            $total->where('created_at','<=',$date_end." 23:59:59");
//        }
        $this->data['analytics']['total']['price'] = $total->sum('price');


        $total1 = DB::table('miss_booking')->where('status',1);
        $total1->where('created_at','>=',date('Y-m-d')." 00:00:00");
        $total1->where('created_at','<=',date('Y-m-d')." 23:59:59");
        $this->data['analytics']['total']['today'] = $total1->count();

//        $total = DB::table('shop_order_excel')
//            ->where('fullname','!=','')
//            ->where('company','!=','KOGYJA')
//            ->where('public','1');
//
//        if(!is_null($user_id) && !empty($user_id)){
//            $total->where('admin_id',$user_id);
//        }
//
////        if(!empty($date_start) && !empty($date_end)){
////            $total->where('order_create_date','>=',$date_start." 00:00:00");
////            $total->where('order_create_date','<=',$date_end." 23:59:59");
////        }
//        $total = $total->count();
//
//        $total1 = DB::table('shop_order_excel')
//            ->where('fullname','!=','')
//            ->where('type','Info')
//            ->where('company','=','KOGYJA')
//            ->where('public','1');
//
//        if(!is_null($user_id) && !empty($user_id)){
//            $total1->where('admin_id',$user_id);
//        }
////        if(!empty($date_start) && !empty($date_end)){
////            $total1->where('order_create_date','>=',$date_start." 00:00:00");
////            $total1->where('order_create_date','<=',$date_end." 23:59:59");
////        }
//        $total1 = $total1->count();
//
//        $this->data['analytics']['total'] = $total1 + $total;
//
//
//
//        $this->data['analytics']['success'] = DB::table('shop_order_excel')
//            ->where('fullname','!=','')
//            ->where('status',1)->where('public','1');
//        if(!is_null($user_id) && !empty($user_id)){
//            $this->data['analytics']['success']->where('admin_id',$user_id);
//        }
//        if(!empty($date_start) && !empty($date_end)) {
//
//            $this->data['analytics']['success']->where('order_create_date', '>=', $date_start . " 00:00:00");
//            $this->data['analytics']['success']->where('order_create_date', '<=', $date_end . " 23:59:59");
//        }
//        $this->data['analytics']['success'] =  $this->data['analytics']['success']->where('status',1)->count();
//
//        $this->data['analytics']['padding'] = DB::table('shop_order_excel')->where('public',1)
//            ->where('fullname','!=','')
//        ;
//        if(!is_null($user_id) && !empty($user_id)){
//            $this->data['analytics']['padding']->where('admin_id',$user_id);
//        }
//        if(!empty($date_start) && !empty($date_end)) {
//
//            $this->data['analytics']['padding']->where('order_create_date', '>=', $date_start . " 00:00:00");
//            $this->data['analytics']['padding']->where('order_create_date', '<=', $date_end . " 23:59:59");
//        }
//        $this->data['analytics']['padding'] = $this->data['analytics']['padding']->where('status',2)->count();
//        $this->data['analytics']['cancel'] = DB::table('shop_order_excel')
//            ->where('fullname','!=','')
//        ;
//        if(!is_null($user_id) && !empty($user_id)){
//            $this->data['analytics']['cancel']->where('admin_id',$user_id);
//        }
//        if(!empty($date_start) && !empty($date_end)) {
//            $this->data['analytics']['cancel']->where('order_create_date', '>=', $date_start . " 00:00:00");
//            $this->data['analytics']['cancel']->where('order_create_date', '<=', $date_end . " 23:59:59");
//        }
//        $this->data['analytics']['cancel'] = $this->data['analytics']['cancel']->where('status',2)->count();
//
////        $this->data['analytics']['today'] = DB::table('shop_order_excel')
////            ->where('fullname','!=','')
////            ->where('public',1)
////            ->where('updated_at','>=',date('Y-m-d')." 00:00:00")
////            ->where('updated_at','<=',date('Y-m-d')." 23:59:59");
////        if(!is_null($user_id) && !empty($user_id)){
////            $this->data['analytics']['today']->where('admin_id',$user_id);
////        }
////        $this->data['analytics']['today'] =  $this->data['analytics']['today']->count();
//
//        $this->data['analytics']['price'] = DB::table('shop_order_excel')
//            ->where('fullname','!=','')
//            ->where('public',1)
//            ->where('order_create_date','>=',date('Y-m-d')." 00:00:00")
//            ->where('order_create_date','<=',date('Y-m-d')." 23:59:59");
//
//        if(!is_null($user_id) && !empty($user_id)){
//            $this->data['analytics']['price']->where('admin_id',$user_id);
//        }
//        $this->data['analytics']['price'] =  $this->data['analytics']['price']->sum('order_price');
        $this->data['analytics']['sql'] = logs_sql();

        return $this->render('dashboard.list',[]);
    }
}