<?php
return [
    'routers'=>[
        'backend'=>[
            'guest'=>[
                "namespace"=>"User\Http\Controllers",
                "controller"=>"AuthController",
                "router"=>[
                    "login"=>[
                        "url"=>"/login",
                        "action"=>"getLogin",
                        "name"=>"backend:login",
                        "guard"=>""
                    ],
                    "login:post"=>[
                        "url"=>"/login/action",
                        "action"=>"postLogin",
                        "method"=>["post"],
                        "guard"=>""
                    ],
                    "logout"=>[
                        "url"=>"/logout",
                        "action"=>"logout",
                        "method"=>["post"],
                        "name"=>"backend:logout"
                    ],
                ]
            ],
            'user'=>[
                "namespace"=>"User\Http\Controllers",
                "controller"=>"UserController",
                "acl"=>"user",
                "router"=>[
                    "list"=>[
                        "url"=>"/user"
                    ],
                ]
            ],
            'user:role'=>[
                "namespace"=>"User\Http\Controllers",
                "controller"=>"RoleController",
                "acl"=>"user:role",
                "router"=>[
                    "list"=>[
                        "url"=>"/user/role"
                    ],

                ]
            ],
        ]
    ]
];